In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
iris=pd.read_csv("iris.csv")

In [2]:
#Shuffling the data for improving the results
iris = iris.sample(frac=1).reset_index(drop=True)
print(iris)

     sepal.length  sepal.width  petal.length  petal.width     variety
0             7.2          3.6           6.1          2.5   Virginica
1             7.3          2.9           6.3          1.8   Virginica
2             7.2          3.2           6.0          1.8   Virginica
3             5.1          3.8           1.9          0.4      Setosa
4             5.3          3.7           1.5          0.2      Setosa
5             6.1          3.0           4.6          1.4  Versicolor
6             6.0          2.2           5.0          1.5   Virginica
7             5.0          3.5           1.6          0.6      Setosa
8             6.8          3.0           5.5          2.1   Virginica
9             4.6          3.4           1.4          0.3      Setosa
10            4.4          3.0           1.3          0.2      Setosa
11            5.8          2.7           4.1          1.0  Versicolor
12            6.3          2.5           5.0          1.9   Virginica
13            5.4   

In [3]:
X = iris[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
X = np.array(X)
print(X)
print("Shape of X",X.shape)

[[7.2 3.6 6.1 2.5]
 [7.3 2.9 6.3 1.8]
 [7.2 3.2 6.  1.8]
 [5.1 3.8 1.9 0.4]
 [5.3 3.7 1.5 0.2]
 [6.1 3.  4.6 1.4]
 [6.  2.2 5.  1.5]
 [5.  3.5 1.6 0.6]
 [6.8 3.  5.5 2.1]
 [4.6 3.4 1.4 0.3]
 [4.4 3.  1.3 0.2]
 [5.8 2.7 4.1 1. ]
 [6.3 2.5 5.  1.9]
 [5.4 3.  4.5 1.5]
 [5.7 4.4 1.5 0.4]
 [5.7 2.6 3.5 1. ]
 [5.1 3.8 1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [6.7 3.3 5.7 2.1]
 [5.  2.3 3.3 1. ]
 [6.7 2.5 5.8 1.8]
 [4.9 3.1 1.5 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.8 3.4 1.6 0.2]
 [5.  3.4 1.5 0.2]
 [7.1 3.  5.9 2.1]
 [6.1 2.6 5.6 1.4]
 [5.8 2.8 5.1 2.4]
 [4.8 3.1 1.6 0.2]
 [6.5 3.  5.5 1.8]
 [5.2 3.4 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [6.4 2.8 5.6 2.1]
 [4.8 3.  1.4 0.1]
 [6.1 2.8 4.  1.3]
 [6.5 3.  5.8 2.2]
 [5.4 3.9 1.3 0.4]
 [6.3 2.8 5.1 1.5]
 [5.9 3.  4.2 1.5]
 [6.3 3.4 5.6 2.4]
 [6.3 2.3 4.4 1.3]
 [5.1 3.5 1.4 0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [6.  3.4 4.5 1.6]
 [5.1 3.5 1.4 0.3]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.5 0.4]
 [5.7 2.5 5.  2. ]
 [7.6 3.  6.

Encoding cells as Setosa-0,Versicolor-1,Virginica-2 then to [1,0,0] for Setosa,[0,1,0] for Versicolor,[0,0,1] for Virginica

In [4]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse=False)

In [5]:
Y = iris.variety
print(Y)
Y = one_hot_encoder.fit_transform(np.array(Y).reshape(-1, 1))
print(Y)

0       Virginica
1       Virginica
2       Virginica
3          Setosa
4          Setosa
5      Versicolor
6       Virginica
7          Setosa
8       Virginica
9          Setosa
10         Setosa
11     Versicolor
12      Virginica
13     Versicolor
14         Setosa
15     Versicolor
16         Setosa
17         Setosa
18         Setosa
19      Virginica
20      Virginica
21     Versicolor
22      Virginica
23         Setosa
24         Setosa
25         Setosa
26         Setosa
27         Setosa
28      Virginica
29      Virginica
          ...    
120    Versicolor
121    Versicolor
122     Virginica
123        Setosa
124        Setosa
125    Versicolor
126        Setosa
127        Setosa
128     Virginica
129     Virginica
130    Versicolor
131     Virginica
132    Versicolor
133    Versicolor
134        Setosa
135     Virginica
136    Versicolor
137     Virginica
138     Virginica
139    Versicolor
140     Virginica
141    Versicolor
142     Virginica
143    Versicolor
144       

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120, 3)


In [7]:
def NeuralNetwork(X_train, Y_train, X_val=None, Y_val=None, epochs=10, nodes=[], lr=0.15):
    hidden_layers = len(nodes)-1
    weights = InitializeWeights(nodes)
    for epoch in range(1, epochs+1):
        weights=Train(X_train, Y_train, lr, weights)
        if epoch%10==0:
            print("Epoch {}".format(epoch))
            print("Training Accuracy:{}".format(Accuracy(X_train, Y_train, weights)))
    return weights

In [8]:
def InitializeWeights(nodes):
    """Initialize weights with random values in [0, 1] (including bias)"""
    layers, weights = len(nodes), []
    
    for i in range(1, layers):
        w = [[np.random.uniform(-1, 1) for k in range(nodes[i-1] + 1)]
              for j in range(nodes[i])]
        weights.append(np.matrix(w))
    
    return weights

In [9]:
def ForwardPropagation(x, weights, layers):
    activations, layer_input = [x], x
    for j in range(layers):
        activation = Sigmoid(np.dot(layer_input, weights[j].T))
        activations.append(activation)
        layer_input = np.append(1, activation) # Augment with bias
    
    return activations

In [10]:
def BackPropagation(y, activations, weights, layers):
    outputFinal = activations[-1]
    error = np.matrix(y - outputFinal) # Error at output
    
    for j in range(layers, 0, -1):
        currActivation = activations[j]
        
        if(j > 1):
            # Augment previous activation
            prevActivation = np.append(1, activations[j-1])
        else:
            # First hidden layer, prevActivation is input (without bias)
            prevActivation = activations[0]
        
        delta = np.multiply(error, SigmoidDerivative(currActivation))
        weights[j-1] += lr * np.multiply(delta.T, prevActivation)

        w = np.delete(weights[j-1], [0], axis=1) # Remove bias from weights
        error = np.dot(delta, w) # Calculate error for current layer
    
    return weights

In [11]:
def Train(X, Y, lr, weights):
    layers = len(weights)
    for i in range(len(X)):
        x, y = X[i], Y[i]
        x = np.matrix(np.append(1, x)) # Augment feature vector
        
        activations = ForwardPropagation(x, weights, layers)
        weights = BackPropagation(y, activations, weights, layers)

    return weights

In [12]:
def Sigmoid(x):
    return 1 / (1 + np.exp(-x))

def SigmoidDerivative(x):
    return np.multiply(x, 1-x)

In [13]:
def Predict(item, weights):
    layers = len(weights)
    item = np.append(1, item) # Augment feature vector
    
    ##_Forward Propagation_##
    activations = ForwardPropagation(item, weights, layers)
    
    outputFinal = activations[-1].A1
    index = FindMaxActivation(outputFinal)

    # Initialize prediction vector to zeros
    y = [0 for i in range(len(outputFinal))]
    y[index] = 1  # Set guessed class to 1

    return y # Return prediction vector


def FindMaxActivation(output):
    """Find max activation in output"""
    m, index = output[0], 0
    for i in range(1, len(output)):
        if(output[i] > m):
            m, index = output[i], i
    
    return index

In [14]:
def Accuracy(X, Y, weights):
    """Run set through network, find overall accuracy"""
    correct = 0

    for i in range(len(X)):
        x, y = X[i], list(Y[i])
        guess = Predict(x, weights)

        if(y == guess):
            # Guessed correctly
            correct += 1

    return correct / len(X)

In [15]:
f = len(X[0]) # Number of features
o = len(Y[0]) # Number of outputs / classes
print(f)
print(o)
layers = [4,10,10,3] # Number of nodes in layers
lr, epochs = 0.15, 100

weights = NeuralNetwork(X_train, Y_train, epochs=epochs, nodes=layers, lr=lr)

4
3
Epoch 10
Training Accuracy:0.6416666666666667
Epoch 20
Training Accuracy:0.7916666666666666
Epoch 30
Training Accuracy:0.925
Epoch 40
Training Accuracy:0.9833333333333333
Epoch 50
Training Accuracy:0.975
Epoch 60
Training Accuracy:0.975
Epoch 70
Training Accuracy:0.975
Epoch 80
Training Accuracy:0.975
Epoch 90
Training Accuracy:0.975
Epoch 100
Training Accuracy:0.975


In [16]:
print("Testing Accuracy: {}".format(Accuracy(X_test, Y_test, weights)))

Testing Accuracy: 0.9333333333333333
